services:
  qBittorrent:
    interval: 3h
    ip_source:
      type: "static"
      value: "74.118.126.97"
    port_source:
      type: "file"
      path: "./tmp/qbittorrent/qBittorrent/qBittorrent.conf"
      pattern: 'Session\\Port=(\d+)'
      # match_group: 1  ‚Üê Default
