services:
  qBittorrent:
    interval: "3h"
    ip_source:
      type: "http"
      url: "https://api.ipify.org?format=json"
      json_path: "ip"
      proxy: "http://localhost:8888"
    port_source:
      type: "file"
      path: "./tmp/qbittorrent/qBittorrent/qBittorrent.conf"
      pattern: 'Session\\Port=(\d+)'
      # match_group: 1  ‚Üê Default
