services:
  qBittorrent:
    interval: "3h"
    ip_source:
      type: "http"
      url: "http://localhost:8000/v1/publicip/ip"
      json_path: "public_ip"
    port_source:
      type: "file"
      path: "./tmp/qbittorrent/qBittorrent/qBittorrent.conf"
      pattern: 'Session\\Port=(\d+)'
      # match_group: 1  ‚Üê Default
